Update ci
BBVAEngineering/ember-alerter pull request #1
Opened 2019-04-10 16:01 UTC by shokmaster

2019-04-15 07:56 UTC, adrigzr requested changes

2019-04-15 07:56 UTC, adrigzr commented on .releaserc
> +}
Try to update to new config style:

```
{
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        "@semantic-release/changelog",
        "@semantic-release/npm",
        "@semantic-release/git",
        "@semantic-release/github"
    ]
}
```

2019-04-15 07:56 UTC, adrigzr commented on package.json
> +  "repository": "",
Fill in `repository`.

2019-04-22 07:28 UTC, shokmaster commented on .releaserc
> +}
done!

2019-04-22 07:29 UTC, shokmaster commented on package.json
> +  "repository": "",
done!

2019-04-22 09:10 UTC, adrigzr submitted a review, later dismissed

2019-04-22 09:45 UTC, josex2r approved these changes

2019-04-22 10:02 UTC, merged

2019-04-22 10:50 UTC, shokmaster commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on [GitHub release](https://github.com/BBVAEngineering/ember-alerter/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: